/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.kramhal.multi;

public class Starter
{
    public String info() {
        return "starter";
    }

    public static void main(String[] args)
    {
        System.out.println(new Starter().info() + " and " + new Module().info());
    }
}
